apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: vote-ui
  name: vote-ui
spec:
  port:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
  to:
    kind: Service
    name: vote-ui
    weight: 100
